defaults: &defaults
  app:
    title: "За город!"

    asset_host: http://zagorod21.ru/

    default_url_options: &default_url_options
      host: zagorod21.ru
      port: 80

  action_mailer: &action_mailer
    raise_delivery_errors: false
    default_url_options:
      <<: *default_url_options

  mailer_defaults:
    <<: *action_mailer
    from: 'noreply@zagorod21.ru'

development:
  <<: *defaults
  action_mailer:
    <<: *action_mailer
    delivery_method: :smtp
    smtp_settings:
      address: localhost
      port: 1025   # mailcatcher
    raise_delivery_errors: true

test:
  <<: *defaults
  capybara:
    port: 57500

  action_mailer:
    <<: *action_mailer
    delivery_method: :test

production:
  <<: *defaults

stage:
  <<: *defaults
